apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyc-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-service
  template:
    metadata:
      labels:
        app: kyc-service
    spec:
      containers:
        - name: kyc-service
          image: fintech-kyc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fintech-config
            - secretRef:
                name: fintech-secrets
          volumeMounts:
            - name: kyc-storage
              mountPath: /app/storage
      volumes:
        - name: kyc-storage
          persistentVolumeClaim:
            claimName: kyc-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-service
spec:
  selector:
    app: kyc-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
